-- Enable foreign key constraints
PRAGMA foreign_keys = ON;

-- Insert logos
INSERT INTO logo (id, path, name) VALUES
                                      (1, 'logo/mdi/diploma-icon.svg', 'Diplôme'),
                                      (2, 'logo/mdi/study-icon.svg', 'Étude'),
                                      (3, 'logo/programming_language/front_end/angular-icon.svg', 'Angular'),
                                      (4, 'logo/programming_language/front_end/javascript-icon.svg', 'JavaScript'),
                                      (5, 'logo/programming_language/front_end/reactjs-icon.svg', 'React.Js'),
                                      (6, 'logo/programming_language/front_end/sass-icon.svg', 'Sass'),
                                      (7, 'logo/programming_language/front_end/svelte-icon.svg', 'Svelte'),
                                      (8, 'logo/programming_language/front_end/typescript-icon.svg', 'TypeScript'),
                                      (9, 'logo/programming_language/front_end/vuejs-icon.svg', 'Vue.js'),
                                      (10, 'logo/programming_language/front_end/css-icon.svg', 'CSS'),
                                      (11, 'logo/programming_language/front_end/html5-icon.svg', 'HTML5'),
                                      (12, 'logo/programming_language/protocol/rest-api-icon.svg', 'REST API'),
                                      (13, 'logo/programming_language/protocol/webrtc-icon.svg', 'WebRTC'),
                                      (14, 'logo/programming_language/protocol/websocket-icon.svg', 'WebSocket'),
                                      (15, 'logo/programming_language/database/mysql-icon.svg', 'MySQL'),
                                      (16, 'logo/programming_language/database/postgresql-icon.svg', 'PostgreSQL'),
                                      (17, 'logo/programming_language/database/sqlite-icon.svg', 'SQLite'),
                                      (18, 'logo/programming_language/back_end/java-icon.svg', 'Java'),
                                      (19, 'logo/programming_language/back_end/laravel-icon.svg', 'Laravel'),
                                      (20, 'logo/programming_language/back_end/leptos-icon.svg', 'Leptos'),
                                      (21, 'logo/programming_language/back_end/lua-icon.svg', 'Lua'),
                                      (22, 'logo/programming_language/back_end/nodejs-icon.svg', 'Node.js'),
                                      (23, 'logo/programming_language/back_end/php-icon.svg', 'PHP'),
                                      (24, 'logo/programming_language/back_end/rust-icon.svg', 'Rust'),
                                      (25, 'logo/programming_language/back_end/spring-icon.svg', 'Spring'),
                                      (26, 'logo/programming_language/back_end/tauri-icon.svg', 'Tauri'),
                                      (27, 'logo/programming_language/platform/linux-icon.svg', 'Linux'),
                                      (28, 'logo/programming_language/platform/windows-icon.svg', 'Windows'),
                                      (29, 'logo/programming_language/back_end/actix-icon.svg', 'Actix'),
                                      (30, 'logo/programming_language/back_end/axum-icon.svg', 'Axum'),
                                      (31, 'logo/company/technopli.png', 'Technopli'),
                                      (32, 'logo/company/irouicome.png', 'IrOuiCome'),
                                      (33, 'logo/company/astree_software.png', 'Astrée Software'),
                                      (34, 'logo/mdi/location-icon.svg', 'Location'),
                                      (35, 'logo/programming_language/librairy/argon2.png', 'Argon2'),
                                      (36, 'logo/programming_language/librairy/barrel.png', 'Barrel'),
                                      (37, 'logo/programming_language/librairy/bevy.svg', 'Bevy'),
                                      (38, 'logo/programming_language/tool/biomejs.svg', 'Biome.Js'),
                                      (39, 'logo/mdi/no-logo.svg', 'No logo'),
                                      (40, 'logo/programming_language/front_end/qwik.svg', 'Qwik'),
                                      (41, 'logo/programming_language/librairy/refinery.svg', 'Refinery'),
                                      (42, 'logo/programming_language/librairy/tokio.svg', 'Tokio'),
                                      (43, 'logo/programming_language/librairy/tracing.png', 'Tracing'),
                                      (44, 'logo/programming_language/librairy/threejs.svg', 'Three.Js'),
                                      (45, 'logo/programming_language/librairy/serde.png', 'Serde'),
                                      (46, 'logo/programming_language/devops_and_infrastructure/github-icon.svg', 'Github'),
                                      (47, 'logo/programming_language/devops_and_infrastructure/gitlab-icon.svg', 'Gitlab'),
                                      (48, 'logo/programming_language/devops_and_infrastructure/jenkins-icon.svg', 'Jenkins'),
                                      (49, 'logo/programming_language/devops_and_infrastructure/postman-icon.svg', 'Postman')
;

-- Insert technology categories
INSERT INTO technology_category (id, title, description) VALUES
                                                             (1, 'Front-End', 'Ce que l''utilisateur voit et avec quoi il interagit sur un site'),
                                                             (2, 'Protocole', 'Les règles qui permettent aux applications et sites de communiquer entre eux'),
                                                             (3, 'Base de donnée', 'Gestion et stockage des données d''une application ou d''un site web'),
                                                             (4, 'Back-End', 'Le back-end gère les données et le fonctionnement en arrière-plan'),
                                                             (5, 'Plateforme', 'Les plateformes sont les systèmes qui exécutent les applications'),
                                                             (6, 'Librairies', 'Ajoute des fonctionnalités prêtes à l''emploi pour simplifier le développement'),
                                                             (7, 'DevOps & Infrastructure', 'Tout ce qui permet de déployer, faire tourner, automatiser et surveiller les applications en production');

-- Insert technologies
INSERT INTO technology (id, name, technology_category_id, logo_id) VALUES
                                                                       (1, 'Angular', 1, 3),
                                                                       (2, 'JavaScript', 1, 4),
                                                                       (3, 'React', 1, 5),
                                                                       (4, 'Sass', 1, 6),
                                                                       (5, 'Svelte', 1, 7),
                                                                       (6, 'TypeScript', 1, 8),
                                                                       (7, 'Vue.js', 1, 9),
                                                                       (8, 'CSS', 1, 10),
                                                                       (9, 'HTML5', 1, 11),
                                                                       (10, 'REST API', 2, 12),
                                                                       (11, 'WebRTC', 2, 13),
                                                                       (12, 'WebSocket', 2, 14),
                                                                       (13, 'MySQL', 3, 15),
                                                                       (14, 'PostgreSQL', 3, 16),
                                                                       (15, 'SQLite', 3, 17),
                                                                       (16, 'Java', 4, 18),
                                                                       (17, 'Laravel', 4, 19),
                                                                       (18, 'Leptos', 4, 20),
                                                                       (19, 'Lua', 4, 21),
                                                                       (20, 'Node.js', 4, 22),
                                                                       (21, 'PHP', 4, 23),
                                                                       (22, 'Rust', 4, 24),
                                                                       (23, 'Spring', 4, 25),
                                                                       (24, 'Tauri', 4, 26),
                                                                       (25, 'Linux', 5, 27),
                                                                       (26, 'Windows', 5, 28),
                                                                       (27, 'Actix', 4, 29),
                                                                       (28, 'Axum', 4, 30),
                                                                       (29, 'argon2', 6, 35),
                                                                       (30, 'barrel', 6, 36),
                                                                       (31, 'bevy', 6, 37),
                                                                       (32, 'biome.js', 7, 38),
                                                                       (33, 'criterion.rs', 7, 39),
                                                                       (34, 'Qwik', 1, 40),
                                                                       (35, 'Refinery', 6, 41),
                                                                       (36, 'Sqlx', 6, 39),
                                                                       (37, 'Tokio', 6, 42),
                                                                       (38, 'Tracing', 6, 43),
                                                                       (39, 'Three.Js', 6, 44),
                                                                       (40, 'Stylance', 6, 39),
                                                                       (41, 'Log', 6, 39),
                                                                       (42, 'Serde', 6, 45),
                                                                       (43, 'Thiserror', 6, 39),
                                                                       (44, 'Tower', 6, 39)
;

-- Insert project statuses
INSERT INTO project_status (id, name) VALUES
                                          (1, 'Idea'),
                                          (2, 'Planned'),
                                          (3, 'InProgress'),
                                          (4, 'OnHold'),
                                          (5, 'Cancelled'),
                                          (6, 'Completed'),
                                          (7, 'Pending'),
                                          (8, 'Archived');

-- Insert projects
INSERT INTO project (id, status_id, description, title, stacks, url_to_project) VALUES
    (1, 3, 'A personal portfolio project built using Server-Side Rendering (SSR) with Leptos and Axum, showcasing modern Rust-based web technologies.', 'portfolio-ssr', '[18,28,38,36,44,43,42,41,40]', 'https://github.com/The-Pac/portfolio-ssr');

-- Insert careers
INSERT INTO careers (id, title, year, parent_id, technology_id, logo_id) VALUES
                                                                             (1, 'Bac', 2019, NULL, NULL, 1),
                                                                             (2, 'BTS Systèmes Numériques Informatique et Réseaux', 2019, 1, NULL, 2),
                                                                             (3, 'Diplôme BTS Systèmes Numériques Informatique et Réseaux', 2021, 2, NULL, 1),
                                                                             (4, 'Java', 2020, 2, 16, NULL),
                                                                             (5, 'Php', 2020, 2, 21, NULL),
                                                                             (6, 'Node.Js', 2020, 2, 20, NULL),
                                                                             (7, 'Mysql', 2020, 2, 13, NULL),
                                                                             (8, 'Html', 2020, 2, 11, NULL),
                                                                             (9, 'Css', 2020, 2, 8, NULL),
                                                                             (10, 'Windows', 2019, 2, 26, NULL),
                                                                             (11, 'Linux', 2019, 2, 25, NULL),
                                                                             (12, 'Technopli', 2020, 2, NULL, 31),
                                                                             (23, 'Licence Informatique développement', 2021, 3, NULL, 2),
                                                                             (13, 'Irouicome', 2022, 23, NULL, 32),
                                                                             (14, 'Rest Api', 2022, 23, 10, NULL),
                                                                             (15, 'Laravel', 2022, 23, 17, NULL),
                                                                             (16, 'React.Js', 2022, 23, 3, NULL),
                                                                             (17, 'Sqlite', 2022, 23, 15, NULL),
                                                                             (18, 'Tauri', 2022, 23, 24, NULL),
                                                                             (19, 'Rust', 2022, 23, 22, NULL),
                                                                             (20, 'Vue.Js', 2022, 23, 7, NULL),
                                                                             (22, 'Typescript', 2022, 23, 6, NULL),
                                                                             (24, 'Diplôme Licence Informatique développement', 2022, 23, NULL, 1),
                                                                             (25, 'Astrée software', 2022, 24, NULL, 33),
                                                                             (26, 'Spring', 2023, 25, 23, NULL),
                                                                             (27, 'Angular', 2023, 25, 1, NULL),
                                                                             (29, 'Postgresql', 2023, 25, 14, NULL),
                                                                             (30, 'Svelte', 2023, 25, 5, NULL),
                                                                             (31, 'Axum', 2023, 25, 28, NULL),
                                                                             (32, 'Actix', 2023, 25, 27, NULL),
                                                                             (28, 'Leptos', 2024, 33, 18, NULL),
                                                                             (33, 'Now', 2024, 25, NULL, 34),
                                                                             (34, 'Enerdis Memo4', 2020, 4, NULL, 46),
                                                                             (35, 'Commande SAV', 2020, 4, NULL, 46),
                                                                             (36, 'Portfolio SSR', 2026, 28, NULL, 46),
                                                                             (37, 'Utopac', 2025, 19, NULL, 46),
                                                                             (38, 'R6 sound visualization', 2025, 19, NULL, 46),
                                                                             (39, 'Pac Gif', 2025, 19, NULL, 46),
                                                                             (40, 'The search letter', 2022, 19, NULL, 46),
                                                                             (41, 'Peeper', 2022, 20, NULL, 46),
                                                                             (42, 'Superviseur', 2022, 4, NULL, 46),
                                                                             (43, 'Chatbox IRC', 2022, 4, NULL, 46),
                                                                             (44, 'Pac car companion', 2025, 19, NULL, 46)
;