pub mod about_me_view;
pub mod career_map_view;
pub mod contact_view;
pub mod introduction_view;
pub mod projects_view;
pub mod recommendations_view;
pub mod technical_stacks_view;
pub mod website_performances_view;
pub mod svg_icon;
